import Home from './home.png';
import Menu from './menu.png';
import Pesanan from './pesanan.png';
import Profil from './profil.png';
import Qr from './QRCODE.png';
import pickup from './iconpickup.jpg';
import takeaway from './icontake.jpg';
import foods from './iconfood.jpg';
import drinks from './icondrink.jpg';
import pastries from './iconpastries.jpg';
export {Home, Menu, Pesanan, Profil,Qr,pickup,takeaway,foods,drinks,pastries};      
